nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:3000']
        allow_headers: ['Content-Type']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    
    paths:
        '^/': ~
