<?php

declare(strict_types=1);

namespace App\Dto\Ingredient;

use App\Entity\Ingredient\IngredientNutrition;

final readonly class IngredientNutritionDto
{
    public function __construct(
        public float $nrjKj,
        public float $nrjKcal,
        public float $eau,
        public float $sel,
        public float $sodium,
        public float $magnesium,
        public float $phosphore,
        public float $potassium,
        public float $calcium,
        public float $manganese,
        public float $fer,
        public float $cuivre,
        public float $zinc,
        public float $selenium,
        public float $iode,
        public float $proteines,
        public float $glucides,
        public float $sucres,
        public float $fructose,
        public float $galactose,
        public float $lactose,
        public float $glucose,
        public float $maltose,
        public float $saccharose,
        public float $amidon,
        public float $polyols,
        public float $fibres,
        public float $lipides,
        public float $ags,
        public float $agmi,
        public float $agpi,
        public float $ag040,
        public float $ag060,
        public float $ag080,
        public float $ag100,
        public float $ag120,
        public float $ag140,
        public float $ag160,
        public float $ag180,
        public float $ag181Ole,
        public float $ag182Lino,
        public float $ag183ALino,
        public float $ag204Ara,
        public float $ag205Epa,
        public float $ag206Dha,
        public float $retinol,
        public float $betaCarotene,
        public float $vitamineD,
        public float $vitamineE,
        public float $vitamineK1,
        public float $vitamineK2,
        public float $vitamineC,
        public float $vitamineB1,
        public float $vitamineB2,
        public float $vitamineB3,
        public float $vitamineB5,
        public float $vitamineB6,
        public float $vitamineB12,
        public float $vitamineB9,
        public float $alcool,
        public float $acidesOrganiques,
        public float $cholesterol,
    ) {
    }

    public static function fromEntity(IngredientNutrition $n): self
    {
        return new self(
            nrjKj: $n->getNrjKj(),
            nrjKcal: $n->getNrjKcal(),
            eau: $n->getEau(),
            sel: $n->getSel(),
            sodium: $n->getSodium(),
            magnesium: $n->getMagnesium(),
            phosphore: $n->getPhosphore(),
            potassium: $n->getPotassium(),
            calcium: $n->getCalcium(),
            manganese: $n->getManganese(),
            fer: $n->getFer(),
            cuivre: $n->getCuivre(),
            zinc: $n->getZinc(),
            selenium: $n->getSelenium(),
            iode: $n->getIode(),
            proteines: $n->getProteines(),
            glucides: $n->getGlucides(),
            sucres: $n->getSucres(),
            fructose: $n->getFructose(),
            galactose: $n->getGalactose(),
            lactose: $n->getLactose(),
            glucose: $n->getGlucose(),
            maltose: $n->getMaltose(),
            saccharose: $n->getSaccharose(),
            amidon: $n->getAmidon(),
            polyols: $n->getPolyols(),
            fibres: $n->getFibres(),
            lipides: $n->getLipides(),
            ags: $n->getAgs(),
            agmi: $n->getAgmi(),
            agpi: $n->getAgpi(),
            ag040: $n->getAg040(),
            ag060: $n->getAg060(),
            ag080: $n->getAg080(),
            ag100: $n->getAg100(),
            ag120: $n->getAg120(),
            ag140: $n->getAg140(),
            ag160: $n->getAg160(),
            ag180: $n->getAg180(),
            ag181Ole: $n->getAg181Ole(),
            ag182Lino: $n->getAg182Lino(),
            ag183ALino: $n->getAg183ALino(),
            ag204Ara: $n->getAg204Ara(),
            ag205Epa: $n->getAg205Epa(),
            ag206Dha: $n->getAg206Dha(),
            retinol: $n->getRetinol(),
            betaCarotene: $n->getBetaCarotene(),
            vitamineD: $n->getVitamineD(),
            vitamineE: $n->getVitamineE(),
            vitamineK1: $n->getVitamineK1(),
            vitamineK2: $n->getVitamineK2(),
            vitamineC: $n->getVitamineC(),
            vitamineB1: $n->getVitamineB1(),
            vitamineB2: $n->getVitamineB2(),
            vitamineB3: $n->getVitamineB3(),
            vitamineB5: $n->getVitamineB5(),
            vitamineB6: $n->getVitamineB6(),
            vitamineB12: $n->getVitamineB12(),
            vitamineB9: $n->getVitamineB9(),
            alcool: $n->getAlcool(),
            acidesOrganiques: $n->getAcidesOrganiques(),
            cholesterol: $n->getCholesterol(),
        );
    }
}
