<?php

declare(strict_types=1);

namespace App\MessageHandler\Ingredient\Ingredient;

final readonly class IngredientNutritionInput
{
    public function __construct(
        public ?float $nrjKj = null,
        public ?float $nrjKcal = null,
        public ?float $eau = null,
        public ?float $sel = null,
        public ?float $sodium = null,
        public ?float $magnesium = null,
        public ?float $phosphore = null,
        public ?float $potassium = null,
        public ?float $calcium = null,
        public ?float $manganese = null,
        public ?float $fer = null,
        public ?float $cuivre = null,
        public ?float $zinc = null,
        public ?float $selenium = null,
        public ?float $iode = null,
        public ?float $proteines = null,
        public ?float $glucides = null,
        public ?float $sucres = null,
        public ?float $fructose = null,
        public ?float $galactose = null,
        public ?float $lactose = null,
        public ?float $glucose = null,
        public ?float $maltose = null,
        public ?float $saccharose = null,
        public ?float $amidon = null,
        public ?float $polyols = null,
        public ?float $fibres = null,
        public ?float $lipides = null,
        public ?float $ags = null,
        public ?float $agmi = null,
        public ?float $agpi = null,
        public ?float $ag040 = null,
        public ?float $ag060 = null,
        public ?float $ag080 = null,
        public ?float $ag100 = null,
        public ?float $ag120 = null,
        public ?float $ag140 = null,
        public ?float $ag160 = null,
        public ?float $ag180 = null,
        public ?float $ag181Ole = null,
        public ?float $ag182Lino = null,
        public ?float $ag183ALino = null,
        public ?float $ag204Ara = null,
        public ?float $ag205Epa = null,
        public ?float $ag206Dha = null,
        public ?float $retinol = null,
        public ?float $betaCarotene = null,
        public ?float $vitamineD = null,
        public ?float $vitamineE = null,
        public ?float $vitamineK1 = null,
        public ?float $vitamineK2 = null,
        public ?float $vitamineC = null,
        public ?float $vitamineB1 = null,
        public ?float $vitamineB2 = null,
        public ?float $vitamineB3 = null,
        public ?float $vitamineB5 = null,
        public ?float $vitamineB6 = null,
        public ?float $vitamineB12 = null,
        public ?float $vitamineB9 = null,
        public ?float $alcool = null,
        public ?float $acidesOrganiques = null,
        public ?float $cholesterol = null,
    ) {
    }
}
